[package]
name = "fintool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
inquire = { version = "0.6.2", features = ["date"] }
file = "1.0.0"
savefile = "0.16.2"
rusqlite = "0.30.0"
