[package]
name = "ofx2fin"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_xml_rs = "0.8.1"
regex = "1.11.1"
shared_lib = { path = "../../shared_lib"}