[package]
name = "shared_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
strum = "0.27.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

